Repository GoormPinIt/pin-it, pull requests merged in 2025-01, with the labels that each got.

#19 [Feat] firebase 로그인, 회원가입 코드 수정
  src/components/Header.tsx
  src/features/authSlice.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: feature

#38 [Feat] 회원가입 아이디 중복 검사
  src/hooks/useDebounce.ts
  src/pages/Signup.tsx
Labels: feature

#39 [Feat] 핀 꾸미기 기능
  src/App.tsx
  src/components/NavBar.tsx
  src/pages/PhotoEditPage.tsx
Labels: feature

#40 [Feat] 핀 꾸미기 기능 구현 수정
  src/App.tsx
Labels: feature

#45 [Feat] 계정 삭제 로직 변경
  src/components/AccountManagement.tsx
Labels: feature

#56 [Fix] 스토리 로딩 처리
  src/assets/loading.gif
  src/pages/StoryPage.tsx
Labels: bugfix

#60 [Fix] 새로 고침 시 페이지 유지
  src/App.tsx
  src/features/authSlice.tsx
Labels: bugfix

#67 [Feat] 저장된 핀 클릭시 상세페이지 이동
  src/App.tsx
  src/components/MasonryLayout.tsx
  src/components/Profile.tsx
  src/components/ScrollTop.tsx
  src/pages/AllPinsPage.tsx
  src/pages/BoardDetails.tsx
Labels: feature

#69 Design : 헤더 검색바 UI 변경
  src/components/Header.tsx
Labels: design
