Repository GoormPinIt/pin-it, pull requests merged in 2025-02, with the labels that each got.

#71 [Design] 스토리 활성화 여부 시각적 표시
  src/components/StoryList.tsx
Labels: design

#72 [Feat] toast 로그인 ui 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/Header.tsx
  src/pages/Login.tsx
Labels: feature

#76 [Design] 로그아웃 상태에서 검색바 비활성화
  src/components/Header.tsx
Labels: design

#78 [Feat] 스토리 삭제 기능
  src/pages/CreateStory.tsx
  src/pages/StoryPage.tsx
Labels: feature

#79 [Feat] 상단 네비게이션 프로필 상태
  src/components/EditProfile.tsx
  src/components/Header.tsx
  src/features/authSlice.tsx
Labels: feature

#84 [Fix] 헤더 프로필 상태
  src/components/EditProfile.tsx
  src/components/Header.tsx
  src/features/authSlice.tsx
Labels: bugfix

#85 [Design] 프로필 수정 완료 시 알림 메시지 전달
  src/components/EditProfile.tsx
  src/components/UserTag.tsx
Labels: design

#86 [Feat] 검색 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/Header.tsx
  src/components/MasonryLayout.tsx
  src/components/Pin.tsx
  src/components/Profile.tsx
  src/pages/AllPinsPage.tsx
  src/pages/PinBuilder.tsx
  src/pages/SearchResultPage.tsx
Labels: feature

#88 [Fix] 저장 시 모든 핀에도 추가되도록 수정
  src/components/Pin.tsx
  src/components/SaveDropdown.tsx
  src/features/boardSlice.tsx
Labels: bugfix

#92 [Feat] 검색어 유지 리셋
  src/App.tsx
  src/components/Header.tsx
  src/components/Pin.tsx
  src/features/searchSlice.tsx
  src/store.tsx
Labels: feature

#99 [Feat] 다른 유저 프로필에서 메시지 전송 및 프로필 보내기
  src/components/Modal.tsx
  src/components/Profile.tsx
Labels: feature

#104 [Fix] cors 이미지 다운로드
  .firebaserc
  firebase.json
  package-lock.json
  package.json
  server/server.mjs
  src/components/Pin.tsx
  src/pages/PinPage.tsx
Labels: bugfix

#106 [Fix] stacking context 문제 해결
  src/components/BoardCreateModal.tsx
  src/components/InviteModal.tsx
  src/components/MergeModal.tsx
  src/components/Profile.tsx
  src/components/SaveDropdown.tsx
  src/components/SimpleBoardCreateModal.tsx
  src/pages/BoardDetails.tsx
Labels: bugfix
